### ISSUE TITLE
Receiving MissingMethodException when calling sample code

### ISSUE THREAD

**Issue by forReason** [wilsonvargas/ScreenshotPlugin#15]
Given the following code:
```
public async void takeScreenShot()
{
        var stream = new System.IO.MemoryStream(await CrossScreenshot.Current.CaptureAsync());
        //Bitmap foo = BitmapFactory.DecodeStream(stream);
        //SaveBitmap(foo);
}
```
The following Exception arises in the first satement:
System.MissingMethodException: 'Method not found: Android.App.Activity Xamarin.Essentials.Platform.get_CurrentActivity()'

**Comment by wilsonvargas** [comment]
Which version of Xamarin.Forms do you use?
