### ISSUE TITLE
Access file path is denied for android platform 

### ISSUE THREAD

**Issue by osamaelhosany** [wilsonvargas/ScreenshotPlugin#4]
**Describe the bug**
I cant access my file after I got screenshot in android platform 

**To Reproduce**
just call 
 var path = await CrossScreenshot.Current.CaptureAndSaveAsync();

**Expected behavior**
I get working path 

**Screenshots**

**Please complete the following information:**
- Which version of the Screenshot do you use? 1.0.16
- Which version of Xamarin.Forms do you use? 3.1.0.583944
- Which OS are you talking about? android api 25

the error said

**Comment by wilsonvargas** [comment]
do you add permission to android manifest?

**Comment by wilsonvargas** [comment]
Did you add permission to Android manifest?

**Comment by wilsonvargas** [comment]
I'm closing the issue as no further response from user. Feel free to re-open if you run into issues around this again or there are further comments.
