### ISSUE TITLE
Lost Reference ImageData

### ISSUE THREAD

**Issue by ITMEU** [wilsonvargas/ScreenshotPlugin#7]
Hi Bro, i hope you´re so fine.

i get a problem when i´m using this line

"ImageData.Source = ImageSource.FromStream(() => stream);"

show the next error 'ImageData" does exist in the current context.

can you help me please , what i need to do??

thaks bro

**Comment by wilsonvargas** [comment]
ImageData is your declared image in your XAML file. See this [sample ](https://github.com/wilsonvargas/ScreenshotPlugin/tree/master/sample)

XAML code:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:SampleScreenShot"
             x:Class="SampleScreenShot.MainPage">

    <StackLayout HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
        <Frame CornerRadius="50" BackgroundColor="Black">
            <Image x:Name="ImageData" Aspect="AspectFill" HeightRequest="250" WidthRequest="100" />
        </Frame>
        <Label x:Name="label" />
        <Button Text="Take Screenshot!" Clicked="Button_Clicked" />
        <Button Text="Takse and Save Screenshot!" Clicked="Button_Clicked_1" />
    </StackLayout>
</ContentPage>

And in your code behind:


    private async void Button_Clicked(object sender, EventArgs e)
    {
        var stream1 = new MemoryStream(await CrossScreenshot.Current.CaptureAsync());
        ImageData.Source = ImageSource.FromStream(() => stream1);
    }
