### ISSUE TITLE
CaptureAndSaveAsync saving the same picture over and over again

### ISSUE THREAD

**Issue by luisrr1590** [wilsonvargas/ScreenshotPlugin#8]
I'm generating a QR Code...once generated I automatically save the screenshot and get the path....then I go back one page and generate another QR Code but when saving the screenshot this time the saved image is the same as previous.....haven´t found a way to dispose of the previous capture without closing the app.

the new path and image is correctly generated and saved....but the screenshot are all the same...the QR Code changes in my app but in the screenshot is always the first generated QR Code.

**To Reproduce**
1. with a button save a screenshot with CaptureAndSaveAsync
2. go back to the button page
3. press the button again

**Expected behavior**
every time the button is pressed the generated screenshot is different from the last one

**Comment by wilsonvargas** [comment]
This solved in this PR #9
